# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: AudioData.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'AudioData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x41udioData.proto\x12\x08\x66oxglove\x1a\x0cheader.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x81\x01\n\x0b\x41udioConfig\x12\x13\n\x0bsample_rate\x18\x01 \x01(\r\x12\x10\n\x08\x63hannels\x18\x02 \x01(\r\x12\x11\n\tbit_depth\x18\x03 \x01(\r\x12\x0e\n\x06\x66ormat\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65vice_name\x18\x05 \x01(\t\x12\x13\n\x0bperiod_size\x18\x06 \x01(\r\"\xe1\x01\n\tAudioData\x12+\n\x06header\x18\x01 \x01(\x0b\x32\x1b.arnold.common.proto.Header\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\t\x12%\n\x06\x63onfig\x18\x03 \x01(\x0b\x32\x15.foxglove.AudioConfig\x12\x12\n\naudio_data\x18\x04 \x01(\x0c\x12\x14\n\x0csample_count\x18\x05 \x01(\r\x12\x16\n\x0e\x63hunk_duration\x18\x06 \x01(\x01\x12\x16\n\x0e\x63hunk_sequence\x18\x07 \x01(\r\x12\x14\n\x0ctotal_chunks\x18\x08 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AudioData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCONFIG']._serialized_start=77
  _globals['_AUDIOCONFIG']._serialized_end=206
  _globals['_AUDIODATA']._serialized_start=209
  _globals['_AUDIODATA']._serialized_end=434
# @@protoc_insertion_point(module_scope)
