# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: BoxAnnotation.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'BoxAnnotation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2
import Vector3_pb2 as Vector3__pb2
import Quaternion_pb2 as Quaternion__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x42oxAnnotation.proto\x12\x08\x66oxglove\x1a\x0cheader.proto\x1a\rVector3.proto\x1a\x10Quaternion.proto\"\x9b\x01\n\tSingleBox\x12!\n\x06\x63\x65nter\x18\x01 \x01(\x0b\x32\x11.foxglove.Vector3\x12\x1f\n\x04size\x18\x02 \x01(\x0b\x32\x11.foxglove.Vector3\x12)\n\x0borientation\x18\x03 \x01(\x0b\x32\x14.foxglove.Quaternion\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x11\n\tsem_label\x18\x05 \x01(\t\"`\n\rBoxAnnotation\x12\"\n\x05\x62oxes\x18\x01 \x03(\x0b\x32\x13.foxglove.SingleBox\x12+\n\x06header\x18\n \x01(\x0b\x32\x1b.arnold.common.proto.Headerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'BoxAnnotation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SINGLEBOX']._serialized_start=81
  _globals['_SINGLEBOX']._serialized_end=236
  _globals['_BOXANNOTATION']._serialized_start=238
  _globals['_BOXANNOTATION']._serialized_end=334
# @@protoc_insertion_point(module_scope)
