# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ChannelData.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'ChannelData.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x43hannelData.proto\x12\x08\x66oxglove\"/\n\tTopicInfo\x12\x13\n\x0bschema_name\x18\x01 \x01(\t\x12\r\n\x05topic\x18\x02 \x01(\t\"4\n\tTopicList\x12\'\n\ntopic_info\x18\x01 \x03(\x0b\x32\x13.foxglove.TopicInfo\"h\n\x0b\x43hannelInfo\x12\x13\n\x0bschema_name\x18\x01 \x01(\t\x12\x14\n\x0cpublish_time\x18\x02 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x11\n\tdata_size\x18\x04 \x01(\x03\x12\r\n\x05topic\x18\x05 \x01(\t\"o\n\x0b\x43hannelData\x12)\n\ntopic_list\x18\x01 \x01(\x0b\x32\x13.foxglove.TopicListH\x00\x12-\n\x0c\x63hannel_info\x18\x02 \x01(\x0b\x32\x15.foxglove.ChannelInfoH\x00\x42\x06\n\x04\x64\x61tab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ChannelData_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOPICINFO']._serialized_start=31
  _globals['_TOPICINFO']._serialized_end=78
  _globals['_TOPICLIST']._serialized_start=80
  _globals['_TOPICLIST']._serialized_end=132
  _globals['_CHANNELINFO']._serialized_start=134
  _globals['_CHANNELINFO']._serialized_end=238
  _globals['_CHANNELDATA']._serialized_start=240
  _globals['_CHANNELDATA']._serialized_end=351
# @@protoc_insertion_point(module_scope)
