# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CircleAnnotation.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'CircleAnnotation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Color_pb2 as Color__pb2
import Point2_pb2 as Point2__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x43ircleAnnotation.proto\x12\x08\x66oxglove\x1a\x0b\x43olor.proto\x1a\x0cPoint2.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd7\x01\n\x10\x43ircleAnnotation\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\"\n\x08position\x18\x02 \x01(\x0b\x32\x10.foxglove.Point2\x12\x10\n\x08\x64iameter\x18\x03 \x01(\x01\x12\x11\n\tthickness\x18\x04 \x01(\x01\x12#\n\nfill_color\x18\x05 \x01(\x0b\x32\x0f.foxglove.Color\x12&\n\routline_color\x18\x06 \x01(\x0b\x32\x0f.foxglove.Colorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CircleAnnotation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CIRCLEANNOTATION']._serialized_start=97
  _globals['_CIRCLEANNOTATION']._serialized_end=312
# @@protoc_insertion_point(module_scope)
