# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FrameTransforms.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'FrameTransforms.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FrameTransform_pb2 as FrameTransform__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x46rameTransforms.proto\x12\x08\x66oxglove\x1a\x14\x46rameTransform.proto\"?\n\x0f\x46rameTransforms\x12,\n\ntransforms\x18\x01 \x03(\x0b\x32\x18.foxglove.FrameTransformb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FrameTransforms_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAMETRANSFORMS']._serialized_start=57
  _globals['_FRAMETRANSFORMS']._serialized_end=120
# @@protoc_insertion_point(module_scope)
