# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Grid.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'Grid.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PackedElementField_pb2 as PackedElementField__pb2
import Pose_pb2 as Pose__pb2
import Vector2_pb2 as Vector2__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nGrid.proto\x12\x08\x66oxglove\x1a\x18PackedElementField.proto\x1a\nPose.proto\x1a\rVector2.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x02\n\x04Grid\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\t\x12\x1c\n\x04pose\x18\x03 \x01(\x0b\x32\x0e.foxglove.Pose\x12\x14\n\x0c\x63olumn_count\x18\x04 \x01(\x07\x12$\n\tcell_size\x18\x05 \x01(\x0b\x32\x11.foxglove.Vector2\x12\x12\n\nrow_stride\x18\x06 \x01(\x07\x12\x13\n\x0b\x63\x65ll_stride\x18\x07 \x01(\x07\x12,\n\x06\x66ields\x18\x08 \x03(\x0b\x32\x1c.foxglove.PackedElementField\x12\x0c\n\x04\x64\x61ta\x18\t \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Grid_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRID']._serialized_start=111
  _globals['_GRID']._serialized_end=373
# @@protoc_insertion_point(module_scope)
