# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: header.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'header.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cheader.proto\x12\x13\x61rnold.common.proto\"D\n\x05Input\x12\x12\n\ntopic_name\x18\x01 \x01(\t\x12\x14\n\x0csequence_num\x18\x02 \x01(\r\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\"\x99\x01\n\x06Header\x12\x13\n\x0bmodule_name\x18\x01 \x01(\t\x12\x14\n\x0csequence_num\x18\x02 \x01(\r\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\x12\x12\n\ntopic_name\x18\x04 \x01(\t\x12\x11\n\texpect_hz\x18\x05 \x01(\x01\x12*\n\x06inputs\x18\x06 \x03(\x0b\x32\x1a.arnold.common.proto.Inputb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'header_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INPUT']._serialized_start=37
  _globals['_INPUT']._serialized_end=105
  _globals['_HEADER']._serialized_start=108
  _globals['_HEADER']._serialized_end=261
# @@protoc_insertion_point(module_scope)
