# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ImageAnnotations.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'ImageAnnotations.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import CircleAnnotation_pb2 as CircleAnnotation__pb2
import PointsAnnotation_pb2 as PointsAnnotation__pb2
import TextAnnotation_pb2 as TextAnnotation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16ImageAnnotations.proto\x12\x08\x66oxglove\x1a\x16\x43ircleAnnotation.proto\x1a\x16PointsAnnotation.proto\x1a\x14TextAnnotation.proto\"\x94\x01\n\x10ImageAnnotations\x12+\n\x07\x63ircles\x18\x01 \x03(\x0b\x32\x1a.foxglove.CircleAnnotation\x12*\n\x06points\x18\x02 \x03(\x0b\x32\x1a.foxglove.PointsAnnotation\x12\'\n\x05texts\x18\x03 \x03(\x0b\x32\x18.foxglove.TextAnnotationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ImageAnnotations_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEANNOTATIONS']._serialized_start=107
  _globals['_IMAGEANNOTATIONS']._serialized_end=255
# @@protoc_insertion_point(module_scope)
