# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: LinePrimitive.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'LinePrimitive.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Color_pb2 as Color__pb2
import Point3_pb2 as Point3__pb2
import Pose_pb2 as Pose__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13LinePrimitive.proto\x12\x08\x66oxglove\x1a\x0b\x43olor.proto\x1a\x0cPoint3.proto\x1a\nPose.proto\"\xaf\x02\n\rLinePrimitive\x12*\n\x04type\x18\x01 \x01(\x0e\x32\x1c.foxglove.LinePrimitive.Type\x12\x1c\n\x04pose\x18\x02 \x01(\x0b\x32\x0e.foxglove.Pose\x12\x11\n\tthickness\x18\x03 \x01(\x01\x12\x17\n\x0fscale_invariant\x18\x04 \x01(\x08\x12 \n\x06points\x18\x05 \x03(\x0b\x32\x10.foxglove.Point3\x12\x1e\n\x05\x63olor\x18\x06 \x01(\x0b\x32\x0f.foxglove.Color\x12\x1f\n\x06\x63olors\x18\x07 \x03(\x0b\x32\x0f.foxglove.Color\x12\x0f\n\x07indices\x18\x08 \x03(\x07\"4\n\x04Type\x12\x0e\n\nLINE_STRIP\x10\x00\x12\r\n\tLINE_LOOP\x10\x01\x12\r\n\tLINE_LIST\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LinePrimitive_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LINEPRIMITIVE']._serialized_start=73
  _globals['_LINEPRIMITIVE']._serialized_end=376
  _globals['_LINEPRIMITIVE_TYPE']._serialized_start=324
  _globals['_LINEPRIMITIVE_TYPE']._serialized_end=376
# @@protoc_insertion_point(module_scope)
