# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ModelPrimitive.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'ModelPrimitive.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Color_pb2 as Color__pb2
import Pose_pb2 as Pose__pb2
import Vector3_pb2 as Vector3__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14ModelPrimitive.proto\x12\x08\x66oxglove\x1a\x0b\x43olor.proto\x1a\nPose.proto\x1a\rVector3.proto\"\xb7\x01\n\x0eModelPrimitive\x12\x1c\n\x04pose\x18\x01 \x01(\x0b\x32\x0e.foxglove.Pose\x12 \n\x05scale\x18\x02 \x01(\x0b\x32\x11.foxglove.Vector3\x12\x1e\n\x05\x63olor\x18\x03 \x01(\x0b\x32\x0f.foxglove.Color\x12\x16\n\x0eoverride_color\x18\x04 \x01(\x08\x12\x0b\n\x03url\x18\x05 \x01(\t\x12\x12\n\nmedia_type\x18\x06 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x07 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ModelPrimitive_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MODELPRIMITIVE']._serialized_start=75
  _globals['_MODELPRIMITIVE']._serialized_end=258
# @@protoc_insertion_point(module_scope)
