# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PointCloud.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'PointCloud.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import PackedElementField_pb2 as PackedElementField__pb2
import Pose_pb2 as Pose__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import header_pb2 as header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10PointCloud.proto\x12\x08\x66oxglove\x1a\x18PackedElementField.proto\x1a\nPose.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0cheader.proto\"\xea\x01\n\nPointCloud\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\t\x12\x1c\n\x04pose\x18\x03 \x01(\x0b\x32\x0e.foxglove.Pose\x12\x14\n\x0cpoint_stride\x18\x04 \x01(\x07\x12,\n\x06\x66ields\x18\x05 \x03(\x0b\x32\x1c.foxglove.PackedElementField\x12\x0c\n\x04\x64\x61ta\x18\x06 \x01(\x0c\x12+\n\x06header\x18\x08 \x01(\x0b\x32\x1b.arnold.common.proto.Headerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PointCloud_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POINTCLOUD']._serialized_start=116
  _globals['_POINTCLOUD']._serialized_end=350
# @@protoc_insertion_point(module_scope)
