# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PosesInFrame.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'PosesInFrame.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Pose_pb2 as Pose__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import header_pb2 as header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12PosesInFrame.proto\x12\x08\x66oxglove\x1a\nPose.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0cheader.proto\"\x9b\x01\n\x0cPosesInFrame\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\t\x12\x1d\n\x05poses\x18\x03 \x03(\x0b\x32\x0e.foxglove.Pose\x12+\n\x06header\x18\x08 \x01(\x0b\x32\x1b.arnold.common.proto.Headerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PosesInFrame_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSESINFRAME']._serialized_start=92
  _globals['_POSESINFRAME']._serialized_end=247
# @@protoc_insertion_point(module_scope)
