# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SensorCalibrationParam.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'SensorCalibrationParam.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import header_pb2 as header__pb2
import Pose_pb2 as Pose__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cSensorCalibrationParam.proto\x12\x08\x66oxglove\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0cheader.proto\x1a\nPose.proto\"A\n\x0f\x43\x61meraIntrinsic\x12\n\n\x02\x66x\x18\x01 \x01(\x01\x12\n\n\x02\x66y\x18\x02 \x01(\x01\x12\n\n\x02\x63x\x18\x03 \x01(\x01\x12\n\n\x02\x63y\x18\x04 \x01(\x01\"N\n\x10\x43\x61meraDistortion\x12\n\n\x02k1\x18\x01 \x01(\x01\x12\n\n\x02k2\x18\x02 \x01(\x01\x12\n\n\x02p1\x18\x03 \x01(\x01\x12\n\n\x02p2\x18\x04 \x01(\x01\x12\n\n\x02k3\x18\x05 \x01(\x01\"\xdf\x01\n\x12PineHoleCameraInfo\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\t\x12\r\n\x05width\x18\x02 \x01(\x07\x12\x0e\n\x06height\x18\x03 \x01(\x07\x12\x33\n\x10\x63\x61mera_intrinsic\x18\x04 \x01(\x0b\x32\x19.foxglove.CameraIntrinsic\x12\x35\n\x11\x63\x61mera_distortion\x18\x05 \x01(\x0b\x32\x1a.foxglove.CameraDistortion\x12,\n\x14\x63\x61mera2ego_extrinsic\x18\x06 \x01(\x0b\x32\x0e.foxglove.Pose\"F\n\rExtrinsicInfo\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\t\x12#\n\x0bpose_to_ego\x18\x02 \x01(\x0b\x32\x0e.foxglove.Pose\"\x80\x02\n\x16SensorCalibrationParam\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x32\n\x0c\x63\x61mera_infos\x18\x02 \x03(\x0b\x32\x1c.foxglove.PineHoleCameraInfo\x12)\n\x08imu_info\x18\x03 \x01(\x0b\x32\x17.foxglove.ExtrinsicInfo\x12+\n\nlidar_info\x18\x04 \x01(\x0b\x32\x17.foxglove.ExtrinsicInfo\x12+\n\x06header\x18\x08 \x01(\x0b\x32\x1b.arnold.common.proto.Headerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SensorCalibrationParam_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAMERAINTRINSIC']._serialized_start=101
  _globals['_CAMERAINTRINSIC']._serialized_end=166
  _globals['_CAMERADISTORTION']._serialized_start=168
  _globals['_CAMERADISTORTION']._serialized_end=246
  _globals['_PINEHOLECAMERAINFO']._serialized_start=249
  _globals['_PINEHOLECAMERAINFO']._serialized_end=472
  _globals['_EXTRINSICINFO']._serialized_start=474
  _globals['_EXTRINSICINFO']._serialized_end=544
  _globals['_SENSORCALIBRATIONPARAM']._serialized_start=547
  _globals['_SENSORCALIBRATIONPARAM']._serialized_end=803
# @@protoc_insertion_point(module_scope)
