# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SimObject.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'SimObject.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Pose_pb2 as Pose__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import BoundingBox_pb2 as BoundingBox__pb2
import header_pb2 as header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fSimObject.proto\x12\x08\x66oxglove\x1a\nPose.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x11\x42oundingBox.proto\x1a\x0cheader.proto\";\n\x08LinkInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12!\n\ttransform\x18\x02 \x01(\x0b\x32\x0e.foxglove.Pose\"(\n\tJointInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\"}\n\x0c\x41rticulation\x12#\n\x06joints\x18\x02 \x03(\x0b\x32\x13.foxglove.JointInfo\x12!\n\x05links\x18\x03 \x03(\x0b\x32\x12.foxglove.LinkInfo\x12%\n\tbase_link\x18\x04 \x01(\x0b\x32\x12.foxglove.LinkInfo\"\x8b\x02\n\tSimObject\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x0c\n\x04type\x18\x05 \x01(\t\x12\x1c\n\x04pose\x18\x06 \x01(\x0b\x32\x0e.foxglove.Pose\x12+\n\x0c\x62ounding_box\x18\x07 \x01(\x0b\x32\x15.foxglove.BoundingBox\x12\x13\n\x0bunique_name\x18\x08 \x01(\t\x12\x13\n\x0bmotion_type\x18\t \x01(\t\x12,\n\x0c\x61rticulation\x18\n \x01(\x0b\x32\x16.foxglove.Articulationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SimObject_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LINKINFO']._serialized_start=107
  _globals['_LINKINFO']._serialized_end=166
  _globals['_JOINTINFO']._serialized_start=168
  _globals['_JOINTINFO']._serialized_end=208
  _globals['_ARTICULATION']._serialized_start=210
  _globals['_ARTICULATION']._serialized_end=335
  _globals['_SIMOBJECT']._serialized_start=338
  _globals['_SIMOBJECT']._serialized_end=605
# @@protoc_insertion_point(module_scope)
