# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SparseOccupancyMap.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'SparseOccupancyMap.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import header_pb2 as header__pb2
import Size3D_pb2 as Size3D__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18SparseOccupancyMap.proto\x12\x08\x66oxglove\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0cheader.proto\x1a\x0cSize3D.proto\"\xed\x01\n\x12SparseOccupancyMap\x12$\n\nspace_size\x18\x01 \x01(\x0b\x32\x10.foxglove.Size3D\x12&\n\x0cpc_range_min\x18\x02 \x01(\x0b\x32\x10.foxglove.Size3D\x12&\n\x0cpc_range_max\x18\x03 \x01(\x0b\x32\x10.foxglove.Size3D\x12\x12\n\nresolution\x18\x04 \x01(\x02\x12\x12\n\nocc_stride\x18\x05 \x01(\x07\x12\x0c\n\x04\x64\x61ta\x18\x06 \x01(\x0c\x12+\n\x06header\x18\n \x01(\x0b\x32\x1b.arnold.common.proto.Headerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SparseOccupancyMap_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPARSEOCCUPANCYMAP']._serialized_start=100
  _globals['_SPARSEOCCUPANCYMAP']._serialized_end=337
# @@protoc_insertion_point(module_scope)
