# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SystemInfo.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'SystemInfo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10SystemInfo.proto\x12\x08\x66oxglove\x1a\x0cheader.proto\"\xe7\x01\n\nSystemInfo\x12+\n\x06header\x18\x01 \x01(\x0b\x32\x1b.arnold.common.proto.Header\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\t\x12\x0b\n\x03pid\x18\x03 \x01(\x03\x12\x11\n\tmemory_kb\x18\x04 \x01(\x04\x12\x0e\n\x06rss_kb\x18\x05 \x01(\x04\x12\x13\n\x0b\x63pu_percent\x18\x06 \x01(\x02\x12\x16\n\x0ememory_percent\x18\x07 \x01(\x02\x12\x1d\n\x15io_read_bytes_per_sec\x18\x08 \x01(\x04\x12\x1e\n\x16io_write_bytes_per_sec\x18\t \x01(\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SystemInfo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYSTEMINFO']._serialized_start=45
  _globals['_SYSTEMINFO']._serialized_end=276
# @@protoc_insertion_point(module_scope)
