# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: TactileMeasurement.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'TactileMeasurement.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import header_pb2 as header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18TactileMeasurement.proto\x12\x08\x66oxglove\x1a\x0cheader.proto\"\xc9\x01\n\x12TactileMeasurement\x12+\n\x06header\x18\x01 \x01(\x0b\x32\x1b.arnold.common.proto.Header\x12\x10\n\x08\x66rame_id\x18\x02 \x01(\t\x12\x0c\n\x04rows\x18\x03 \x01(\r\x12\x0c\n\x04\x63ols\x18\x04 \x01(\r\x12\x15\n\rpressure_data\x18\x05 \x03(\x02\x12\x15\n\rpressure_unit\x18\x06 \x01(\t\x12\x14\n\x0cmin_pressure\x18\x07 \x01(\x02\x12\x14\n\x0cmax_pressure\x18\x08 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TactileMeasurement_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TACTILEMEASUREMENT']._serialized_start=53
  _globals['_TACTILEMEASUREMENT']._serialized_end=254
# @@protoc_insertion_point(module_scope)
