# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: TextPrimitive.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'TextPrimitive.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Color_pb2 as Color__pb2
import Pose_pb2 as Pose__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13TextPrimitive.proto\x12\x08\x66oxglove\x1a\x0b\x43olor.proto\x1a\nPose.proto\"\x9a\x01\n\rTextPrimitive\x12\x1c\n\x04pose\x18\x01 \x01(\x0b\x32\x0e.foxglove.Pose\x12\x11\n\tbillboard\x18\x02 \x01(\x08\x12\x11\n\tfont_size\x18\x03 \x01(\x01\x12\x17\n\x0fscale_invariant\x18\x04 \x01(\x08\x12\x1e\n\x05\x63olor\x18\x05 \x01(\x0b\x32\x0f.foxglove.Color\x12\x0c\n\x04text\x18\x06 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'TextPrimitive_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTPRIMITIVE']._serialized_start=59
  _globals['_TEXTPRIMITIVE']._serialized_end=213
# @@protoc_insertion_point(module_scope)
